#!/usr/bin/env python3 
#Imports
from errno import WSAEDQUOT
import os 
import sys
from datetime import datetime
import EXP_PGM as pgm #script for creating views based on raw ECHOEPA data
import viewsToMaterialized as mview #script which creates materialized views of view 
from sqlalchemy import create_engine

#Set paths
os.chdir(os.path.dirname(sys.argv[0]))

#Connect to DB
engine = create_engine("postgresql://postgres@localhost:5432/slim_echoepa", echo=False)

## Creates a lookup table (EXP_PGM) of official ids from the ECHO_EXPORTER table
print("creating a lookup talbe, EXP_PGM")
pgm.build(engine)

#Create materialized views based off of ECHOEPA tables
print("creating materialized views...")
mview.build(engine) #materialized views

print("running sql analyze...")
engine.execute("analyze")