#!/usr/bin/env python3 
#Imports
import csv
import os
import signal
import sys
import subprocess
from datetime import datetime
import re
from sqlalchemy import create_engine

#Set paths
os.chdir(os.path.dirname(sys.argv[0]))

#Connect to DB
engine = create_engine("postgresql://postgres@localhost:5432/slim_echoepa", echo=False)

#Download all zip files in the files.csv and unzip them, then stripping nulls from the csv files.
with open('files.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        uniqueZips={}
        for row in reader:
                        table=row['CSV FILE']
                        location=row['Location']
                        url=row['URL']
                        if location not in uniqueZips.keys():
                                uniqueZips[location] = row
                                if not os.path.isfile('zips/%s' %(location)):
                                        modified=""
                                        while(modified==""):
                                                print("Getting %s" %(url))
                                                print("reading the modified date from the wegetEPA script...")
                                                modified = subprocess.check_output("./wgetEPA %s" %(url), shell=True).decode("utf-8").strip().splitlines()[0]
                                        with engine.connect() as connection:
                                            results = connection.execute("UPDATE \"Last-Modified\" SET modified='%s' WHERE zip = '%s' AND name= '%s'" %(modified,location,table))
                                        if results.rowcount == 0:
                                            with engine.connect() as connection:
                                                results = connection.execute("INSERT INTO \"Last-Modified\" (name,modified,zip) VALUES ('%s','%s','%s')" %(table,modified,location))
                                if not os.path.isfile('CSV/%s.csv' %(table)):
                                        print('Missing CSV file: CSV/%s ...' %(table))
                                        if re.match("csv$",url.lower()):
                                                print("moving the file....%s" %(location))
                                                os.rename("zips/"+location, "CSV/"+location) #move file
                                        elif ".zip" in url.lower():
                                                print("extracting CSV files from the zip file...%s %s" %(location, table))
                                                os.system("./unzipEPA %s %s.csv" %(location,table)) #Unzip

                                print("Stripping nulls from %s.csv ..." %(table))
                                os.system("./stripNulls %s" %(table)) #some csvs failed to import with nulls. this also cuts the CSV (head command)

print("You already downloaded/extracted all CSV files listed in the files.csv!")